// Generated by Claude with the Yahtzee message added by me (with help by Claude to use its CSS)

// Yahtzee Dice Roller

const NUMBER_OF_DICE = 5;
const SERVER_URL = "https://dice-roller-node-fne8b0hvbeaeffhp.centralus-01.azurewebsites.net";
const FORCE_YAHTZEE = false; //Testing the Yahtzee message I added.

// Wakes the server before first roll
async function wakeServer() {
  try {
    const pingResponse = await fetch(`${SERVER_URL}/api/ping`);
    const pingMessage = await pingResponse.text();

    console.log("Server ping:", pingMessage);

    rollAllDice();
  } catch (error) {
    console.error("CORS request failed:", error);
  }
}

// Gets Dice Values from Server
async function rollAllDice() {
  const response = await fetch(`${SERVER_URL}/api/roll`);
  const data = await response.json();

  const roll = data.rolls;
  let total = 0;
  
  if (FORCE_YAHTZEE) {
    for (let i = 0; i < roll.length; i++) {
      roll[i] = 1;
    }
  }

  for (let dieNumber = 1; dieNumber <= NUMBER_OF_DICE; dieNumber++) {
    const result = roll[dieNumber - 1];
    total += result;
    const dieElement = document.querySelector(`.die[data-die="${dieNumber}"]`);
    const valueField = document.getElementById(`value-${dieNumber}`);

    dieElement.setAttribute("data-value", result);
    valueField.value = result;

    // Retrigger the tumble animation even on repeated identical rolls.
    dieElement.classList.remove("is-rolling");
    // Forcing a reflow lets the animation restart cleanly.
    void dieElement.offsetWidth;
    dieElement.classList.add("is-rolling");
  }

  document.getElementById("value-total").value = total;
  let yahtzee = true;
  for (let i = 1; i < roll.length; i++) {
    if (roll[i] !== roll[0]) {
      yahtzee = false;
      break;
    }
  }
  if (yahtzee) {
    showYahtzeeMessage(roll[0]);
  }
}

const rollButton = document.getElementById("roll-button");

rollButton.addEventListener("keydown", (e) => {
  if (e.key === "Enter") rollButton.classList.add("is-pressed");
});

rollButton.addEventListener("keyup", (e) => {
  if (e.key === "Enter") rollButton.classList.remove("is-pressed");
});

const yahtzeeDialog = document.getElementById("yahtzee-dialog");
const yahtzeeMessage = document.getElementById("yahtzee-message");

function showYahtzeeMessage(value) {
  yahtzeeMessage.textContent = `Yahtzee! All five dice show ${value}.`;
  setTimeout(() => {if (!yahtzeeDialog.open) yahtzeeDialog.showModal();}, 600);
}